"""Add new plot fields

Revision ID: f932859fdb0b
Revises: 2d123c762717
Create Date: 2026-09-17 18:16:59.925843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f932859fdb0b'
down_revision: Union[str, None] = '2d123c762717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('plot_type', sa.String(), nullable=True))
    op.add_column('plots', sa.Column('address', sa.String(), nullable=True))
    op.add_column('plots', sa.Column('year_of_registration', sa.String(), nullable=True))
    op.add_column('plots', sa.Column('owner_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'owner_name')
    op.drop_column('plots', 'year_of_registration')
    op.drop_column('plots', 'address')
    op.drop_column('plots', 'plot_type')
    # ### end Alembic commands ###
